# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: "*"
  pull_request:
    branches: ["main"]

jobs:
  run_backend_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/backend/
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --frozen-lockfile
      - name: Type checking
        run: yarn build
      - run: yarn ci:tests
      - run: pwd
      - run: cat coverage/coverage-summary.json
      - name: Generating coverage badges for backend
        uses: jpb06/jest-badges-action@latest
        with:
          branches: main
          coverage-summary-path: /home/runner/work/TDD-Lister/TDD-Lister/src/backend/coverage/coverage-summary.json
          output-folder: /home/runner/work/TDD-Lister/TDD-Lister/src/backend/coverage/
